# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'
use_frameworks!
#消除警告
inhibit_all_warnings!

def share_pods
  pod 'MyLayout'
  pod 'ReactiveObjC'
  pod 'AFNetworking'
  pod 'SDWebImage'
  pod 'Masonry'
end

targetArray = ['HelloSDK','AAASDK','TestHello']
# TestHello对HelloSDK的依赖，使用xcode的target依赖target的方式处理
# 选择TestHello->General->Frameworks, Libraries, and Embedded Content->+ ->HelloSDK.framwork
targetArray.each do |t|
    target t do
      puts t # 打印输出
      share_pods
      if t == "TestHello"
        pod 'SVGAPlayer'
      end
    end
end
#target 'HelloSDK' do
#  # Comment the next line if you don't want to use dynamic frameworks
#   share_pods
#end
#target 'TestHello' do
#  # Comment the next line if you don't want to use dynamic frameworks
#   share_pods
#   pod "SVGAPlayer"
#
#end
